// flow-typed signature: 8842fcc23c7ff98bb4ad70e3c98bae2a
// flow-typed version: <<STUB>>/polymorph-js_v^0.2.2/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'polymorph-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'polymorph-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'polymorph-js/config/rollup.cdn' {
  declare module.exports: any;
}

declare module 'polymorph-js/dist/polymorph' {
  declare module.exports: any;
}

declare module 'polymorph-js/dist/polymorph.min' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib.es2015/constants' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib.es2015/getPath' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib.es2015/index' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib.es2015/interpolate' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib.es2015/operators/arcToCurve' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib.es2015/operators/fillPoints' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib.es2015/operators/fillSegments' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib.es2015/operators/interpolatePath' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib.es2015/operators/normalizePaths' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib.es2015/operators/normalizePoints' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib.es2015/operators/parsePath' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib.es2015/operators/parsePoints' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib.es2015/operators/perimeterPoints' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib.es2015/operators/renderPath' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib.es2015/operators/rotatePoints' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib.es2015/parse' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib.es2015/types' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib.es2015/utilities/browser' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib.es2015/utilities/coalesce' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib.es2015/utilities/createNumberArray' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib.es2015/utilities/distance' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib.es2015/utilities/errors' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib.es2015/utilities/inspect' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib.es2015/utilities/math' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib.es2015/utilities/objects' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib/constants' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib/getPath' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib/index' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib/interpolate' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib/operators/arcToCurve' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib/operators/fillPoints' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib/operators/fillSegments' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib/operators/interpolatePath' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib/operators/normalizePaths' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib/operators/normalizePoints' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib/operators/parsePath' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib/operators/parsePoints' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib/operators/perimeterPoints' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib/operators/renderPath' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib/operators/rotatePoints' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib/parse' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib/types' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib/utilities/browser' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib/utilities/coalesce' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib/utilities/createNumberArray' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib/utilities/distance' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib/utilities/errors' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib/utilities/inspect' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib/utilities/math' {
  declare module.exports: any;
}

declare module 'polymorph-js/lib/utilities/objects' {
  declare module.exports: any;
}

// Filename aliases
declare module 'polymorph-js/config/rollup.cdn.js' {
  declare module.exports: $Exports<'polymorph-js/config/rollup.cdn'>;
}
declare module 'polymorph-js/dist/polymorph.js' {
  declare module.exports: $Exports<'polymorph-js/dist/polymorph'>;
}
declare module 'polymorph-js/dist/polymorph.min.js' {
  declare module.exports: $Exports<'polymorph-js/dist/polymorph.min'>;
}
declare module 'polymorph-js/lib.es2015/constants.js' {
  declare module.exports: $Exports<'polymorph-js/lib.es2015/constants'>;
}
declare module 'polymorph-js/lib.es2015/getPath.js' {
  declare module.exports: $Exports<'polymorph-js/lib.es2015/getPath'>;
}
declare module 'polymorph-js/lib.es2015/index.js' {
  declare module.exports: $Exports<'polymorph-js/lib.es2015/index'>;
}
declare module 'polymorph-js/lib.es2015/interpolate.js' {
  declare module.exports: $Exports<'polymorph-js/lib.es2015/interpolate'>;
}
declare module 'polymorph-js/lib.es2015/operators/arcToCurve.js' {
  declare module.exports: $Exports<'polymorph-js/lib.es2015/operators/arcToCurve'>;
}
declare module 'polymorph-js/lib.es2015/operators/fillPoints.js' {
  declare module.exports: $Exports<'polymorph-js/lib.es2015/operators/fillPoints'>;
}
declare module 'polymorph-js/lib.es2015/operators/fillSegments.js' {
  declare module.exports: $Exports<'polymorph-js/lib.es2015/operators/fillSegments'>;
}
declare module 'polymorph-js/lib.es2015/operators/interpolatePath.js' {
  declare module.exports: $Exports<'polymorph-js/lib.es2015/operators/interpolatePath'>;
}
declare module 'polymorph-js/lib.es2015/operators/normalizePaths.js' {
  declare module.exports: $Exports<'polymorph-js/lib.es2015/operators/normalizePaths'>;
}
declare module 'polymorph-js/lib.es2015/operators/normalizePoints.js' {
  declare module.exports: $Exports<'polymorph-js/lib.es2015/operators/normalizePoints'>;
}
declare module 'polymorph-js/lib.es2015/operators/parsePath.js' {
  declare module.exports: $Exports<'polymorph-js/lib.es2015/operators/parsePath'>;
}
declare module 'polymorph-js/lib.es2015/operators/parsePoints.js' {
  declare module.exports: $Exports<'polymorph-js/lib.es2015/operators/parsePoints'>;
}
declare module 'polymorph-js/lib.es2015/operators/perimeterPoints.js' {
  declare module.exports: $Exports<'polymorph-js/lib.es2015/operators/perimeterPoints'>;
}
declare module 'polymorph-js/lib.es2015/operators/renderPath.js' {
  declare module.exports: $Exports<'polymorph-js/lib.es2015/operators/renderPath'>;
}
declare module 'polymorph-js/lib.es2015/operators/rotatePoints.js' {
  declare module.exports: $Exports<'polymorph-js/lib.es2015/operators/rotatePoints'>;
}
declare module 'polymorph-js/lib.es2015/parse.js' {
  declare module.exports: $Exports<'polymorph-js/lib.es2015/parse'>;
}
declare module 'polymorph-js/lib.es2015/types.js' {
  declare module.exports: $Exports<'polymorph-js/lib.es2015/types'>;
}
declare module 'polymorph-js/lib.es2015/utilities/browser.js' {
  declare module.exports: $Exports<'polymorph-js/lib.es2015/utilities/browser'>;
}
declare module 'polymorph-js/lib.es2015/utilities/coalesce.js' {
  declare module.exports: $Exports<'polymorph-js/lib.es2015/utilities/coalesce'>;
}
declare module 'polymorph-js/lib.es2015/utilities/createNumberArray.js' {
  declare module.exports: $Exports<'polymorph-js/lib.es2015/utilities/createNumberArray'>;
}
declare module 'polymorph-js/lib.es2015/utilities/distance.js' {
  declare module.exports: $Exports<'polymorph-js/lib.es2015/utilities/distance'>;
}
declare module 'polymorph-js/lib.es2015/utilities/errors.js' {
  declare module.exports: $Exports<'polymorph-js/lib.es2015/utilities/errors'>;
}
declare module 'polymorph-js/lib.es2015/utilities/inspect.js' {
  declare module.exports: $Exports<'polymorph-js/lib.es2015/utilities/inspect'>;
}
declare module 'polymorph-js/lib.es2015/utilities/math.js' {
  declare module.exports: $Exports<'polymorph-js/lib.es2015/utilities/math'>;
}
declare module 'polymorph-js/lib.es2015/utilities/objects.js' {
  declare module.exports: $Exports<'polymorph-js/lib.es2015/utilities/objects'>;
}
declare module 'polymorph-js/lib/constants.js' {
  declare module.exports: $Exports<'polymorph-js/lib/constants'>;
}
declare module 'polymorph-js/lib/getPath.js' {
  declare module.exports: $Exports<'polymorph-js/lib/getPath'>;
}
declare module 'polymorph-js/lib/index.js' {
  declare module.exports: $Exports<'polymorph-js/lib/index'>;
}
declare module 'polymorph-js/lib/interpolate.js' {
  declare module.exports: $Exports<'polymorph-js/lib/interpolate'>;
}
declare module 'polymorph-js/lib/operators/arcToCurve.js' {
  declare module.exports: $Exports<'polymorph-js/lib/operators/arcToCurve'>;
}
declare module 'polymorph-js/lib/operators/fillPoints.js' {
  declare module.exports: $Exports<'polymorph-js/lib/operators/fillPoints'>;
}
declare module 'polymorph-js/lib/operators/fillSegments.js' {
  declare module.exports: $Exports<'polymorph-js/lib/operators/fillSegments'>;
}
declare module 'polymorph-js/lib/operators/interpolatePath.js' {
  declare module.exports: $Exports<'polymorph-js/lib/operators/interpolatePath'>;
}
declare module 'polymorph-js/lib/operators/normalizePaths.js' {
  declare module.exports: $Exports<'polymorph-js/lib/operators/normalizePaths'>;
}
declare module 'polymorph-js/lib/operators/normalizePoints.js' {
  declare module.exports: $Exports<'polymorph-js/lib/operators/normalizePoints'>;
}
declare module 'polymorph-js/lib/operators/parsePath.js' {
  declare module.exports: $Exports<'polymorph-js/lib/operators/parsePath'>;
}
declare module 'polymorph-js/lib/operators/parsePoints.js' {
  declare module.exports: $Exports<'polymorph-js/lib/operators/parsePoints'>;
}
declare module 'polymorph-js/lib/operators/perimeterPoints.js' {
  declare module.exports: $Exports<'polymorph-js/lib/operators/perimeterPoints'>;
}
declare module 'polymorph-js/lib/operators/renderPath.js' {
  declare module.exports: $Exports<'polymorph-js/lib/operators/renderPath'>;
}
declare module 'polymorph-js/lib/operators/rotatePoints.js' {
  declare module.exports: $Exports<'polymorph-js/lib/operators/rotatePoints'>;
}
declare module 'polymorph-js/lib/parse.js' {
  declare module.exports: $Exports<'polymorph-js/lib/parse'>;
}
declare module 'polymorph-js/lib/types.js' {
  declare module.exports: $Exports<'polymorph-js/lib/types'>;
}
declare module 'polymorph-js/lib/utilities/browser.js' {
  declare module.exports: $Exports<'polymorph-js/lib/utilities/browser'>;
}
declare module 'polymorph-js/lib/utilities/coalesce.js' {
  declare module.exports: $Exports<'polymorph-js/lib/utilities/coalesce'>;
}
declare module 'polymorph-js/lib/utilities/createNumberArray.js' {
  declare module.exports: $Exports<'polymorph-js/lib/utilities/createNumberArray'>;
}
declare module 'polymorph-js/lib/utilities/distance.js' {
  declare module.exports: $Exports<'polymorph-js/lib/utilities/distance'>;
}
declare module 'polymorph-js/lib/utilities/errors.js' {
  declare module.exports: $Exports<'polymorph-js/lib/utilities/errors'>;
}
declare module 'polymorph-js/lib/utilities/inspect.js' {
  declare module.exports: $Exports<'polymorph-js/lib/utilities/inspect'>;
}
declare module 'polymorph-js/lib/utilities/math.js' {
  declare module.exports: $Exports<'polymorph-js/lib/utilities/math'>;
}
declare module 'polymorph-js/lib/utilities/objects.js' {
  declare module.exports: $Exports<'polymorph-js/lib/utilities/objects'>;
}
