// flow-typed signature: edcfc447b7f10d75d69f32d8ac2aa782
// flow-typed version: <<STUB>>/gatsby-source-shopify_v^1.1.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-source-shopify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-source-shopify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-source-shopify/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby-source-shopify/lib' {
  declare module.exports: any;
}

declare module 'gatsby-source-shopify/nodes' {
  declare module.exports: any;
}

declare module 'gatsby-source-shopify/queries' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-source-shopify/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-source-shopify/gatsby-node'>;
}
declare module 'gatsby-source-shopify/index' {
  declare module.exports: $Exports<'gatsby-source-shopify'>;
}
declare module 'gatsby-source-shopify/index.js' {
  declare module.exports: $Exports<'gatsby-source-shopify'>;
}
declare module 'gatsby-source-shopify/lib.js' {
  declare module.exports: $Exports<'gatsby-source-shopify/lib'>;
}
declare module 'gatsby-source-shopify/nodes.js' {
  declare module.exports: $Exports<'gatsby-source-shopify/nodes'>;
}
declare module 'gatsby-source-shopify/queries.js' {
  declare module.exports: $Exports<'gatsby-source-shopify/queries'>;
}
